version: '3.7'
services:
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   command: python manage.py test

  web:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:

# sudo docker-compose up --build
# sudo docker-compose run test