version: '3.7'
services:
  web:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=amr
  #     - POSTGRES_PASSWORD=24092793
  #     - POSTGRES_DB=iss

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  # postgres_data:

# sudo docker-compose up --build
# sudo docker-compose run test